openapi: 3.0.3
info:
  title: Vue Kotlin Template API
  description: Vue Kotlin Templateの API
  version: 0.2.0

servers:
  - url: http://localhost:8080
    description: ローカル開発環境

tags:
  - name: Health
    description: ヘルスチェック関連
  - name: Auth
    description: 認証関連
  - name: Posts
    description: 投稿関連

paths:
  /health:
    get:
      tags:
        - Health
      summary: ヘルスチェック
      description: サービスの稼働状況を確認します。
      responses:
        "200":
          description: サービスは稼働中です。
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time
                    description: 現在時刻（ISO 8601形式）
                    example: "2026-01-12T10:30:00Z"

  /auth/signup:
    post:
      tags:
        - Auth
      summary: ユーザー登録
      description: 新しいユーザーを登録します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
                - displayName
                - password
              properties:
                userName:
                  type: string
                  description: ログインID（3〜50文字、英数字とアンダースコアのみ）
                  minLength: 3
                  maxLength: 50
                  pattern: "^[a-zA-Z0-9_]+$"
                  example: john_doe
                displayName:
                  type: string
                  description: 表示名（1〜100文字）
                  minLength: 1
                  maxLength: 100
                  example: John Doe
                password:
                  type: string
                  description: パスワード（8文字以上推奨）
                  minLength: 8
                  format: password
                  example: securePassword123
      responses:
        "201":
          description: ユーザー登録成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                  - user
                properties:
                  token:
                    type: string
                    description: JWTアクセストークン
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  user:
                    $ref: "#/components/schemas/User"
        "400":
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: validationError
                message: 1つ以上のフィールドに不正な値が含まれています
                details:
                  - field: userName
                    message: ユーザー名は3文字以上50文字以内で入力してください
                  - field: password
                    message: パスワードは8文字以上で入力してください
        "409":
          description: ユーザー名が既に使用されています
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: duplicate
                message: ユーザー名は既に使用されています

  /auth/login:
    post:
      tags:
        - Auth
      summary: ログイン
      description: ユーザー名とパスワードでログインし、JWTトークンを取得します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
                - password
              properties:
                userName:
                  type: string
                  description: ログインID
                  example: john_doe
                password:
                  type: string
                  description: パスワード
                  format: password
                  example: securePassword123
      responses:
        "200":
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                  - user
                properties:
                  token:
                    type: string
                    description: JWTアクセストークン
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  user:
                    $ref: "#/components/schemas/User"
        "401":
          description: 認証失敗（ユーザー名またはパスワードが間違っています）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: unauthorized
                message: ユーザー名またはパスワードが正しくありません

  /auth/me:
    get:
      tags:
        - Auth
      summary: 現在のユーザー情報取得
      description: JWTトークンから現在ログイン中のユーザー情報を取得します。
      security:
        - BearerAuth: []
      responses:
        "200":
          description: ユーザー情報取得成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: 認証失敗（トークンが無効または期限切れ）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: invalidToken
                message: トークンが無効または期限切れです

  /posts:
    get:
      tags:
        - Posts
      summary: 投稿一覧取得
      description: すべての投稿を新しい順で取得します。
      responses:
        "200":
          description: 投稿一覧の取得に成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"

    post:
      tags:
        - Posts
      summary: 投稿作成
      description: 新しい投稿を作成します。認証が必要です。
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: 投稿本文
                  maxLength: 280
                  example: これは投稿のテキストです
      responses:
        "201":
          description: 投稿の作成に成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: validationError
                message: 1つ以上のフィールドに不正な値が含まれています
                details:
                  - field: content
                    message: 投稿内容を入力してください
        "401":
          description: 認証失敗（トークンが無効または期限切れ）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                type: invalidToken
                message: トークンが無効または期限切れです

components:
  schemas:
    User:
      type: object
      required:
        - id
        - userName
        - displayName
      properties:
        id:
          type: string
          format: uuid
          description: ユーザーID（UUID v4）
          example: 123e4567-e89b-12d3-a456-426614174000
        userName:
          type: string
          description: ログインID
          example: john_doe
        displayName:
          type: string
          description: 表示名
          example: John Doe

    Post:
      type: object
      required:
        - id
        - user
        - content
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: 投稿ID（UUID v4）
          example: 550e8400-e29b-41d4-a716-446655440000
        user:
          $ref: "#/components/schemas/User"
        content:
          type: string
          description: 投稿本文
          maxLength: 280
          example: これは投稿のテキストです
        createdAt:
          type: string
          format: date-time
          description: 投稿日時（ISO 8601形式）
          example: "2026-01-11T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - type
        - message
      properties:
        type:
          type: string
          description: エラータイプ（camelCase形式）
          example: validationError
        message:
          type: string
          description: エラーメッセージ
          example: 1つ以上のフィールドに不正な値が含まれています
        details:
          type: array
          description: エラー詳細（バリデーションエラーなど）
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
                description: エラーが発生したフィールド名
                example: content
              message:
                type: string
                description: フィールド固有のエラーメッセージ
                example: 入力してください

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT認証。ヘッダーに `Authorization: Bearer {token}` を含めてください。"
